name: Build and deploy Node.js app to Azure Web App - manage-school

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Add app_offline.htm (to safely stop the app)
        run: echo "" > ./dist/app_offline.htm

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3018B61C82BC48ABA1C7302A40ED26F0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2F357679FD154532BA1C39FF750AB588 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CE233273CD3343CE863479D57B6BA908 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'manage-school'
          slot-name: 'Production'
          package: ./dist

      - name: Remove app_offline.htm (to bring app back online)
        run: rm ./dist/app_offline.htm
